"""Measures WCAG contrast for the colour tokens against the surfaces they are used on (P10, UX04).
Writes docs/ux/contrast-report.md. Targets: text 4.5:1, non-text indicators 3:1 (section 14.8)."""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), "..")
ASSETS = os.path.join(ROOT, "App", "Resources", "Assets.xcassets")

# iOS system surfaces (approximate sRGB values of semantic colours).
SURFACES = {
    "light": {"grouped": "#F2F2F7", "card": "#FFFFFF"},
    "dark": {"grouped": "#000000", "card": "#1C1C1E"},
}

def load(name):
    data = json.load(open(os.path.join(ASSETS, f"{name}.colorset", "Contents.json")))
    out = {}
    for c in data["colors"]:
        apps = {a["appearance"]: a["value"] for a in c.get("appearances", [])}
        key = ("dark" if apps.get("luminosity") == "dark" else "light") + ("-hc" if apps.get("contrast") == "high" else "")
        comp = c["color"]["components"]
        out[key] = "#" + "".join(f"{int(comp[k], 16):02X}" for k in ("red", "green", "blue"))
    return out

def lum(hexv):
    h = hexv.lstrip("#")
    def ch(v):
        v = int(v, 16) / 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    r, g, b = ch(h[0:2]), ch(h[2:4]), ch(h[4:6])
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def ratio(a, b):
    la, lb = sorted([lum(a), lum(b)], reverse=True)
    return (la + 0.05) / (lb + 0.05)

# (foreground token, background token or surface, kind, where used)
PAIRS = [
    ("AccentColor", "card", "text", "links, tinted labels on cards"),
    ("NeutralUnknown", "card", "text", "unconfirmed / checking labels"),
    ("PassGreen", "card", "text", "check-passed pill text"),
    ("RecordRed", "card", "non-text", "recording dot, Stop outline"),
    ("WarningText", "WarningFill", "text", "warning notice text/icon on warning fill"),
    ("AccentColor", "AccentFill", "text", "tinted buttons"),
    ("#FFFFFF", "RecordButtonFill", "text", "white label on Start/Stop button and session strip"),
    ("#FFFFFF", "AccentButtonFill", "text", "white label on primary button"),
]

rows, failures = [], 0
for mode in ["light", "dark", "light-hc", "dark-hc"]:
    base = mode.split("-")[0]
    for fg, bg, kind, where in PAIRS:
        fgc = fg if fg.startswith("#") else load(fg).get(mode, load(fg)[base])
        bgc = SURFACES[base][bg] if bg in SURFACES[base] else load(bg).get(mode, load(bg)[base])
        r = ratio(fgc, bgc)
        target = 4.5 if kind == "text" else 3.0
        ok = r >= target
        failures += 0 if ok else 1
        rows.append(f"| {mode} | {fg} | {bg} | {where} | {r:.2f}:1 | {target}:1 | {'PASS' if ok else 'FAIL'} |")

report = ["# Contrast report (generated)", "",
          "Generated by `scripts/contrast_check.py` from the asset catalog. System surfaces use their documented sRGB values.",
          "This measures colour pairs; it does not replace on-device legibility review (UX04 physical follow-up, P14).", "",
          "| Appearance | Foreground | Background | Use | Ratio | Target | Result |", "|---|---|---|---|---|---|---|"] + rows + \
         ["", f"**Failures:** {failures}"]
os.makedirs(os.path.join(ROOT, "docs", "ux"), exist_ok=True)
open(os.path.join(ROOT, "docs", "ux", "contrast-report.md"), "w", newline="\n").write("\n".join(report) + "\n")
print("\n".join(rows))
print("failures:", failures)
raise SystemExit(1 if failures else 0)
